### ISSUE TITLE
Phen2Gene package vs publication

### ISSUE THREAD

**Issue by PabloBotas** [WGLab/Phen2Gene#23]
Hi!
Looking into this repository, it seems like it is built to replicate the results from the publication. Am I right?

We are going to deploy Phen2Gene, which means we will probably remove the items that are intended for the publication only. To keep full traceability with you it may make sense if you could split it and we fork the new repository intended for the code of Phen2Gene only. My point is that from my point of view any development we do on the package should point to Wang Lab's Github and with the current status both repositories will quickly diverge.

Suggestion: simply create a copy of this named Phen2Gene-publication (or something like that) and we would work on a fork of this current repository.

The first step for us would be to remove unnecessary files and add a dockerfile.

Any thoughts about this? :)

**Comment by jimhavrilla** [comment]
Hey Pablo,
 
Yes, this sounds like a cool idea.  I discussed with Kai, and we think the best idea, since this repository is in the paper, is to keep this the same URL and we can fork a new URL: `WGLab/Phen2Gene2`.  We can call it Phen2Gene2 and treat it as a tool-only repo (taking out all the extra figure generation stuff and benchmark data if you like) and upgrade it and the databases and all that.  Does that sound good to you?

We certainly are interested in keeping the tool improved and up-to-date and incorporating new databases, and I'm sure Mengge and I would have stake in that.

Please let me know.

Sincerely,

Jim

**Comment by PabloBotas** [comment]
Hi,
Yes, that was my point. Maybe something more explicit that Phen2Gene2? You might want to create a real v2 of Phen2Gene at some point. Maybe something like Phen2Gene-package? I don't know, up to you :)

**Comment by jimhavrilla** [comment]
My hope is any improvements you all make we can also incorporate into v2 if
that is something you're interested in.  I've done that for now (
https://github.com/WGLab/Phen2Gene2) and we'll see where it goes from
there.  I can always change the repo name later.

**Comment by PabloBotas** [comment]
Yes, you are right. That should work :)
